apiVersion: v1
kind: Service
metadata:
  name: jenkins-build-graalvm-service
spec:
  type: NodePort
  selector:
    app: jenkins-build-graalvm
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080