apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-build-graalvm-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard